websocket harness

diff --git a/bin/tau-websocket b/bin/tau-websocket
--- a/bin/tau-websocket
+++ b/bin/tau-websocket
@@ -51,6 +51,15 @@ authenticate() {
     sleep infinity
 }
 
-(authenticate) \
-    | websocat_linux64 wss://tau.cgs.dev/ws/twitch-events/ \
-    | reqreader
+set -o pipefail;
+while true; do
+  (authenticate) \
+      | websocat_linux64 -E wss://tau.cgs.dev/ws/twitch-events/ --ping-interval 10 --ping-timeout 15 \
+      | reqreader
+  FAILED=$?
+  echo "$FAILED"
+  if [[ "$FAILED" -ge 130 ]]; then
+    exit 0
+  fi
+  echo "IT CRASHED, RESTARTING"
+done
diff --git a/bin/twitch-cmds/channel-points b/bin/twitch-cmds/channel-points
--- a/bin/twitch-cmds/channel-points
+++ b/bin/twitch-cmds/channel-points
@@ -61,8 +61,17 @@ msg='{"type":"LISTEN","data":{"topics":["channel-points-channel-v1.56931496"],"a
 ping='{"type": "PING"}'
 
 
-(echo "$msg"; while true; do sleep 280; echo "$ping"; done) \
-    | websocat_linux64 wss://pubsub-edge.twitch.tv \
-    | jq -r --unbuffered 'select(.type == "MESSAGE") | .data.message' \
-    | jq -c --unbuffered '.data.redemption' \
-    | redeem
+set -o pipefail;
+while true; do
+  (echo "$msg"; while true; do sleep 280; echo "$ping"; done) \
+      | websocat_linux64 wss://pubsub-edge.twitch.tv -E --ping-timeout 15 --ping-interval 10 \
+      | jq -r --unbuffered 'select(.type == "MESSAGE") | .data.message' \
+      | jq -c --unbuffered '.data.redemption' \
+      | redeem
+  FAILED=$?
+  echo "$FAILED"
+  if [[ "$FAILED" -ge 130 ]]; then
+    exit 0
+  fi
+  echo "IT CRASHED, RESTARTING"
+done
diff --git a/bin/twitch-cmds/twitch-chat b/bin/twitch-cmds/twitch-chat
--- a/bin/twitch-cmds/twitch-chat
+++ b/bin/twitch-cmds/twitch-chat
@@ -226,13 +226,24 @@ parsechat() {
 }
 reqreader() {
   while IFS= read -r line; do
-    [[ $line == "PING"* ]] && echo "PONG :tmi.twitch.tv\r";
+    [[ $line == "PING"* ]] && echo "PONG :tmi.twitch.tv";
     [[ "$line" == "SYSTEM_EV "* ]] && reply "$(echo $line | sed 's/^SYSTEM_EV //')"
     [[ "$line" == *" PRIVMSG "* ]] && (parsechat "$line" 1>&2; parsecmd "$line")
   done;
   exit 0;
 }
-(echo "CAP REQ :twitch.tv/tags twitch.tv/commands\r\nPASS oauth:${TWITCH_ACCESS_TOKEN}\r\nNICK goodcop_\r\nJOIN #${CHAN}\r"; \
-    </tmp/twitch_tunnel | reqreader) \
-    | websocat_linux64 -E -vvv wss://irc-ws.chat.twitch.tv:443 \
-    | >/tmp/twitch_tunnel
+
+set -o pipefail;
+while true; do
+  (echo "CAP REQ :twitch.tv/tags twitch.tv/commands\r\nPASS oauth:${TWITCH_ACCESS_TOKEN}\r\nNICK goodcop_\r\nJOIN #${CHAN}\r"; \
+      </tmp/twitch_tunnel | reqreader) \
+      | websocat_linux64 -E -vvv wss://irc-ws.chat.twitch.tv:443 --ping-timeout 15 --ping-interval 10 \
+      | >/tmp/twitch_tunnel;
+  FAILED=$?
+  echo "$FAILED"
+  if [[ "$FAILED" -ge 130 ]]; then
+    exit 0
+  fi
+  echo "IT CRASHED, RESTARTING"
+  refresh-token-bot
+done
